

services:
  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    entrypoint: /bin/sh -c "ollama serve & sleep 3 && ollama pull tinyllama && ollama pull nomic-embed-text && wait"
    restart: unless-stopped


  backend:
    build: .
    command: python run.py
    ports:
      - "5000:5000"
    depends_on:
      - ollama

  frontend:
    build: .
    command: streamlit run streamlit_app.py --server.port=8501 --server.address=0.0.0.0
    ports:
      - "8501:8501"
    depends_on:
      - backend

volumes:
  ollama_data:
